### ISSUE TITLE
Problem with calculation of actives

### ISSUE THREAD

**Issue by fredrikw** [eloyfelix/chembl_multitask#1]
I believe there is a problem with the code below:

```python
def set_active(row):
    active = 0
    if row['standard_value'] <= 1000:
        active = 1
    if row['l1'] == 'Ion channel':
        if row['standard_value'] > 10000:
            active = 0
    if row['l2'] == 'Kinase':
        if row['standard_value'] <= 30:
            active = 1
    if row['l2'] == 'Nuclear receptor':
        if row['standard_value'] <= 100:
            active = 1
    if row['l3'] and 'GPCR' in row['l3']:
        if row['standard_value'] <= 100:
            active = 1
    return active
```

As far as I can see, this code will make everything with a standard_value below 1000 active and everything else inactive.
E.g. if we have a compound targeting a kinase with standard_value of 100, this should mark it as active since the first if statement will be true and the activity is not reset after that. On the other hand, an ion channel inhibitor with a standard_value of 3000 will be marked as inactive since the first if statement is false and no changes will be made to the active variable.

I think a better way to write this is:

```python
def set_active(row):
    active = 0
    if row['standard_value'] <= 1000:
        active = 1
    if row['l1'] == 'Ion channel':
        if row['standard_value'] <= 10000:
            active = 1
    if row['l2'] == 'Kinase':
        if row['standard_value'] > 30:
            active = 0
    if row['l2'] == 'Nuclear receptor':
        if row['standard_value'] > 100:
            active = 0
    if row['l3'] and 'GPCR' in row['l3']:
        if row['standard_value'] > 100:
            active = 0
    return active
```

**Comment by eloyfelix** [comment]
You're completely right. I wonder what I did here... It's now fixed.
Many thanks for reporting!

**Comment by eloyfelix** [comment]
dataset also updated here: ftp://ftp.ebi.ac.uk/pub/databases/chembl/blog/pytorch_mtl/
